# Introduction

Climate change has been a hot topic from many years ago. However, we felt that in recent years, the topic of climate change has been mentioned less in the news, maybe due to COVID 19, Russian-Ukrainian wars, Palestinian conflicts, etc. However, climate change is still a very important topic that we should not forget. Despite being very young, we could still notice the changes in the environment around us. For example, I remembered the summers in recent years being hotter than ever before and winters in the past being much colder, then much warmer, to now much colder again. In the past, we often hear in the news about global warming. However, the effect of global warming is not only the increase in temperature, but also result in unpredictable climate such as much colder or hotter winters, more extreme disasters, etc. In history, many civilizations have been destroyed due to climate change. For example, the Roman Empire, Han Dynasty, Ming Dynasty ,etc. all collapsed due to social upheavals resulted from climate change. Therefore, we should not ignore the effects of climate change and should take actions to prevent it. In our project, we will be using the data from the World Bank to analyze the effects of climate change on the economy of different countries. We will also be using the data from the World Bank to analyze the effects of climate change on the economy of different countries. This will include the effect of climate change on GDP, Child mortality rate, population growth, droughts, floods, extreme temperatures, etc. We hope that through our project, we could raise awareness of climate change, convey its averse effects on the economy, and ultimately encourage people to continue taking actions to prevent climate change. After all, we only have one Earth.
